POST http://localhost:8080/accounts
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{ "balance": 100 }

<> 2020-04-29T044058.200.json

###

POST http://localhost:8080/accounts
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{ "balance": 100 }

###

POST http://localhost:8080/accounts
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{ "balance": 100 }

###

POST http://localhost:8080/accounts
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{ "balance": 100 }

###

POST http://localhost:8080/accounts
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{ "balance": 100 }

###

POST http://localhost:8080/accounts
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{ "balance": 100 }

###

POST http://localhost:8080/accounts
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{ "balance": 100 }

###

POST http://localhost:8080/accounts
Accept: */*
Cache-Control: no-cache

{ "balance": 100 }

<> 2020-04-29T043032.415.json

###

